### PR TITLE
Fixed NodeRED template + add TheHive+Cortex+Traefik with TLS docker-compose template

### PR DESCRIPTION
**Pull request by korteke**
Fixed URLs and added little bit of documentation

### CODE REVIEW

**Comment by korteke** [comment]
Gash, now all the changes are in one PR. But two thing:
* Fixed NodeRED template
* Created totally new template for TheHive+Cortex+Traefik with TLS

Yes, there is certificate and corresponding private key in the repo. That self-signed certificate is there because it's easier to test this template if there is all bits&pieces in place.

Fixes #43

**Comment by nadouani** [comment]
Hello @korteke Thanks for the PR. I think you can remove the cert file, isn't?

**Comment by korteke** [comment]
@nadouani Yeah, ofc it can be removed. I was just thinking that it would be easier to test if there is everything in place :) but i remove it, then gh’s builtin security scanner does not complain about that cert.

**Comment by korteke** [comment]
> Hello @korteke Thanks for the PR. I think you can remove the cert file, isn't?

I removed the certificate & private key. 8b12755318fc46147550acaae8d8fb6b6750b417

**Comment by nadouani** [comment]
@all-contributors please add @korteke for code

**Pull request merged**
